config/routes.rb
Rails.application.routes.draw do
  resources :buys
  resources :clients
  resources :sells
  resources :products

end

app/models/buy.rb
class Buy < ActiveRecord::Base
 attr_accessible :Fecha, :cantidad, :proveedor, :total, :id_producto, :descripcion  
 has_many :product 


end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)
    @pro = Product.find_by_id(@buy.id_producto)
    inventario = @pro.cantidad + @buy.cantidad
    @pro.cantidad = inventario 
    @pro.save
  
  date_current = DateTime.now.to_date
  @buy.Fecha = date_current
  total = @buy.cantidad * Product.find_by_id(@buy.id_producto).costo
  @buy.total = total

    respond_to do |format|
      if @buy.save
        format.html { redirect_to @buy, notice: 'Buy was successfully created.' }
        format.json { render :show, status: :created, location: @buy }
      else
        format.html { render :new }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buys/1
  # PATCH/PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url, notice: 'Buy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_params
      params.require(:buy).permit(:Fecha, :cantidad, :proveedor, :total, :id_producto, :descripcion)
    end
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/buys/_form.html.erb
<%= form_for(@buy) do |f| %>
  <% if @buy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
      <% @buy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Fecha %><br>
    <%= f.date_select :Fecha %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :proveedor %><br>
    <%= f.text_field :proveedor %>
  </div>
  <div class="field">
    <%= f.label :id_producto %><br>
    <%= f.number_field :id_producto %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buys/edit.html.erb
<h1>Editing Buy</h1>

<%= render 'form' %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

app/views/buys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buys</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Cantidad</th>
      <th>Proveedor</th>
      <th>Total</th>
      <th>Id producto</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buys.each do |buy| %>
      <tr>
        <td><%= buy.Fecha %></td>
        <td><%= buy.cantidad %></td>
        <td><%= buy.proveedor %></td>
        <td><%= buy.total %></td>
        <td><%= buy.id_producto %></td>
        <td><%= buy.descripcion %></td>
        <td><%= link_to 'Show', buy %></td>
        <td><%= link_to 'Edit', edit_buy_path(buy) %></td>
        <td><%= link_to 'Destroy', buy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy', new_buy_path %>

app/views/buys/new.html.erb
<h1>New Buy</h1>

<%= render 'form' %>

<%= link_to 'Back', buys_path %>

app/views/buys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @buy.Fecha %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @buy.cantidad %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @buy.proveedor %>
</p>

<p>
  <strong>Total:</strong>
  <%= @buy.total %>
</p>

<p>
  <strong>Id producto:</strong>
  <%= @buy.id_producto %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @buy.descripcion %>
</p>

<%= link_to 'Edit', edit_buy_path(@buy) %> |
<%= link_to 'Back', buys_path %>