config/routes.rb
Rails.application.routes.draw do
  resources :buys
  resources :clients
  resources :sells
  resources :products

end

app/models/sell.rb
class Sell < ActiveRecord::Base
attr_accessible :product_id, :fecha_v, :cantidad, :total, :client_id  
belongs_to :product 
belongs_to :client
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  before_action :set_sell, only: [:show, :edit, :update, :destroy]

  # GET /sells
  # GET /sells.json
  def index
    @sells = Sell.all
  end

  # GET /sells/1
  # GET /sells/1.json
  def show
  end

  # GET /sells/new
  def new
    @sell = Sell.new
  end

  # GET /sells/1/edit
  def edit
  end

  # POST /sells
  # POST /sells.json
  def create 

    @sell = Sell.new(sell_params)
    @pro = Product.find_by_id(@sell.product.id)
    inventario = @pro.cantidad - @sell.cantidad
    @pro.cantidad = inventario 
    @pro.save
	

    date_current = DateTime.now.to_date
	@sell.fecha_v = date_current
	total = @sell.cantidad * Product.find_by_id(@sell.product_id).precio
	@sell.total = total
  
    respond_to do |format|
      if @sell.save
        format.html { redirect_to @sell, notice: 'Sell was successfully created.' }
        format.json { render :show, status: :created, location: @sell }
      else
        format.html { render :new }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sells/1
  # PATCH/PUT /sells/1.json
  def update
    respond_to do |format|
      if @sell.update(sell_params)
        format.html { redirect_to @sell, notice: 'Sell was successfully updated.' }
        format.json { render :show, status: :ok, location: @sell }
      else
        format.html { render :edit }
        format.json { render json: @sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sells/1
  # DELETE /sells/1.json
  def destroy
    @sell.destroy
    respond_to do |format|
      format.html { redirect_to sells_url, notice: 'Sell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sell
      @sell = Sell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sell_params
      params.require(:sell).permit(:product_id, :fecha_v, :cantidad, :total, :client_id)
    end
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/sells/_form.html.erb
<%= form_for(@sell) do |f| %>
  <% if @sell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sell.errors.count, "error") %> prohibited this sell from being saved:</h2>

      <ul>
      <% @sell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
 <p id="demo"></p>
<script>
var d = new Date();
document.getElementById("demo").innerHTML = d.toDateString();
</script> 
  
  <div class="field">
    <%= f.label :product_id %><br>
   <select name="sell[product_id]">
      <% Product.all.each do |p| %>
    	<option value="<%= p.id %>"><%= p.nombre %></option>
      <% end %>
    </select>
  </div>
 
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
 <div class="field">
    <%= f.label :cliente %><br>
  <select name="sell[client_id]">
      <% Client.all.each do |c| %>
    	<option value="<%= c.id %>"><%= c.nombre %></option>
      <% end %>
    </select> 
  </div>
 
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sells/edit.html.erb
<h1>Editing Sell</h1>

<%= render 'form' %>

<%= link_to 'Show', @sell %> |
<%= link_to 'Back', sells_path %>

app/views/sells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ventas</h1>

<table>
  <thead>
    <tr>
      <th>Producto</th>
      <th>Fecha </th>
      <th>Cantidad</th>
      <th>Total</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sells.each do |sell| %>
      <tr>
        <td><%= sell.product.nombre %></td>
        <td><%= sell.fecha_v %></td>
        <td><%= sell.cantidad %></td>
        <td><%= sell.total %></td>
        <td><%= sell.client.nombre %></td>
        <td><%= link_to 'Mostrar', sell %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva venta', new_sell_path %>

app/views/sells/new.html.erb
<h1>Venta</h1>

<%= render 'form' %>

<%= link_to 'Back', sells_path %>

app/views/sells/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Prod:</strong>
  <%= @sell.product_id %>
</p>

<p>
  <strong>Fecha v:</strong>
  <%= @sell.fecha_v %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @sell.cantidad %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sell.total %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @sell.client_id %>
</p>

<%= link_to 'Editar', edit_sell_path(@sell) %> |
<%= link_to 'Regresar', sells_path %>